######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 18 20:14:28 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += FingerPad.cpp
