######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 19 03:14:37 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FingerPad.h
SOURCES += FingerPad.cpp
