######################################################################
# Automatically generated by qmake (1.07a) Sun Mar 17 20:47:02 2013
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += Hello.cpp
